Rust Borrow checker prevents swap_data Rust Borrow Self Mut error[E0499]: cannot borrow  as mutable more than once at a time    --> src/face.rs:233:42     | 233 |         self.get_face_piece(a).swapdata(&self.get_face_pieceData(b));     |         ----                   --------  ^^^^ second mutable borrow occurs here     |         |                      |     |         |                      first borrow later used by call     |         first mutable borrow occurs here
Rust Borrow Self
error[E0502]: cannot borrow  as immutable because it is also borrowed as mutable
   --> src/face.rs:233:42
    |
233 |         self.get_face_piece(a).swapdata(&self.get_face_pieceData(b));
    |         ----                   --------  ^^^^ immutable borrow occurs here
    |         |                      |
    |         |                      mutable borrow later used by call
    |         mutable borrow occurs here